/**
 * This file is autogenerated with make_static.sh script
 */

#pragma once

#include <stdlib.h>

namespace homekit::files {

typedef struct {
    size_t size;
    const uint8_t* content;
} StaticFile;

extern const StaticFile index_html;
extern const StaticFile app_js;
extern const StaticFile md5_js;
extern const StaticFile style_css;
extern const StaticFile favicon_ico;

}
